name: iselectaplication1990
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  animated_text_kit: ^2.1.0
  google_fonts: ^0.5.0
  percent_indicator: ^2.1.3
  simple_animations: ^1.3.11
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  firebase_messaging: ^6.0.16
  mask_text_input_formatter: ^1.0.6
  validadores: ^1.0.2
  page_transition: ^1.1.5
  curved_navigation_bar: ^0.3.2
  scoped_model: ^1.0.1
  firebase_storage: ^3.1.6
  image_picker: ^0.6.7
  carousel_pro: ^1.0.0
  flutter_speed_dial: ^1.2.5
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.1
  firebase_core: ^0.4.5
  brasil_fields: ^0.1.0
  url_launcher: ^5.4.10
  smooth_star_rating: ^1.1.1
  filter_list: ^0.0.1
  country_code_picker: ^1.3.15
  flutter_screenutil: ^1.1.0
  animated_theme_switcher: ^1.0.6
  line_awesome_icons: ^1.0.4+2
  shimmer: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/analist.jpg
    - images/celu1.png
    - images/celu2.png
    - images/e1.jpg
    - images/hm.jpg
    - images/homem.jpg
    - images/ideia.jpg
    - images/signUp.jpg
    - images/engine.jpg
    - images/engine2.jpg
    - images/toque1.jpg
    - images/hmazul.jpg
    - images/3.jpg
    - images/tel.jpg
    - images/iphone3.png
    - images/trabalhador.jpg
    - images/gifs/aero.gif
    - images/gifs/caregamento.gif
    - images/gifs/compativel.gif
    - images/gifs/explorer.gif
    - images/gifs/gatos.gif
    - images/gifs/mulher_no_celular.gif
    - images/icons/galeria1.png
    - images/icons/camera.png
    - images/icons/alarma.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
